version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: fcord-backend
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:


# services:
#   fcord-postgres-compose:
#     image: postgres
#     environment: 
#       POSTGRES_USER: username
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: fcord-database
#     ports:
#       - '15432:5432'
#     volumes:
#       - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

#   fcord-pgadmin-compose:
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
#       PGADMIN_DEFAULT_PASSWORD: 'admin'
#     ports:
#       - '16543:80'
#     depends_on:
#       - fcord-postgres-compose

# volumes:
#   database-data: # named volumes can be managed easier using docker-compose

